### ISSUE TITLE
Setting config variables

### ISSUE THREAD

**Issue by acco** [waisbrot/dogstatsde#5]
Thanks for your great work here!

I'm able to configure the lib with environment variables easy, eg `AGENT_ADDRESS`. Everything works great.

However, I can't sort out how to configure via my config file (Elixir). Below is the error I receive immediately after attempting to send my first stat:

```elixir
# in my config.exs
config :dogstatsd, agent_address: "172.17.0.1"

# in iex
iex(1)> :dogstatsd.increment("tests.acco", 1, %{})
:ok
# Then immediately after, this error message prints:
iex(2)> [error] GenServer :"wpool_pool-dogstatsd_worker-1" terminating
** (CaseClauseError) no case clause matching: :badarg
    (worker_pool 3.1.1) /.../deps/worker_pool/src/wpool_process.erl:155: :wpool_process.handle_cast/2
    (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:cast, {:metric, {:timer, [{"apis.airtable.request_time", 1, 1.0, %{}}]}}}}
State: {:state, :"wpool_pool-dogstatsd_worker-1", :dogstatsd_worker, {:state, #Port<0.1861>, "172.17.0.1", 8125, [], %{}}, [queue_manager: :"wpool_pool-dogstatsd_worker-queue-manager", time_checker: :"wpool_pool-dogstatsd_worker-time-checker", worker: {:dogstatsd_worker, []}, workers: 10, overrun_warning: :infinity, overrun_handler: {:error_logger, :warning_report}, workers: 100, worker_opt: [], queue_type: :fifo]}
```

I'm sure I'm just missing something simple -- Any pointers/direction would be much appreciated 🙏 

Thanks,
A

**Comment by waisbrot** [comment]
Well, sadly I haven't been in Erlang (or Elixir) for a while now, so we'll have to figure it out together.

Configuration is handled with Stillir. You can see how it's used here: https://github.com/waisbrot/dogstatsde/blob/master/src/dogstatsd_sup.erl#L19

So you ought to be able to run (in your example)
```
:stillir.get_config(:dogstatsd, :agent_address)
```

and hopefully see your configuration. Try it with both env vars and with config.exs?

**Comment by Fitblip** [comment]
Hi friends, I had the same question. I went digging into the stillir source and found that this is basically a passthrough to `:application.get_env`.

https://github.com/heroku/stillir/blob/1c08f363ef565b06e161c8c59dda0ccd5f47e0ef/src/stillir.erl#L46-L62

Configuration is pretty straight forward then for elixir:

```
config :dogstatsd,
       agent_address: 'localhost',
       global_prefix: 'your_app',
       global_tags: %{something: 'something else'},
       vm_stats_base_key: 'vm'
```

The only thing to note is to use the `'` to ensure you're using charlists and not elixir strings (since the config processing happens in erlang). 

Thanks for the useful library @waisbrot!

**Comment by waisbrot** [comment]
Whoops, I meant to close this after Fitplip's explanation. Thanks for the helpful comment, Fitblip!
